const menuData = [
    {
        id: 1,
        title: 'buttermilk pancakessssssssssssdadasdsdasdhjsg asdcasghdfsv hjvjsadjsa',
        category: 'Breakfast',
        price: 15.99,
        img: 'https://i.pinimg.com/originals/57/48/f6/5748f66613de9ac009fd9337e99b6e6b.jpg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan c `,
    },
    {
        id: 2,
        title: 'diner double',
        category: 'Lunch',
        price: 13.99,
        img: 'https://bakingmischief.com/wp-content/uploads/2022/03/coffee-milkshake-square.jpg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvet`,
    },
    {
        id: 3,
        title: 'godzilla milkshake',
        category: 'Shakes',
        price: 6.99,
        img: 'https://i.pinimg.com/originals/57/48/f6/5748f66613de9ac009fd9337e99b6e6b.jpg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo`,
    },
    {
        id: 4,
        title: 'country delight',
        category: 'Breakfast',
        price: 20.99,
        img: 'https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin  `,
    },
    {
        id: 5,
        title: 'egg attack',
        category: 'Lunch',
        price: 22.99,
        img: 'https://smoothie.school/app/uploads/2020/04/Oreo-Nutella-Milkshake.jpg',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditat `,
    },
    {
        id: 6,
        title: 'oreo dream',
        category: 'Shakes',
        price: 18.99,
        img: 'https://smoothie.school/app/uploads/2020/04/Oreo-Nutella-Milkshake.jpg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: 'bacon overflow',
        category: 'Breakfast',
        price: 8.99,
        img: 'https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
        id: 8,
        title: 'american classic',
        category: 'Lunch',
        price: 12.99,
        img: 'https://img.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg?w=2000',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
        id: 9,
        title: 'quarantine buddy',
        category: 'Shakes',
        price: 16.99,
        img: 'https://smoothie.school/app/uploads/2020/04/Oreo-Nutella-Milkshake.jpg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
        id: 9,
        title: 'quarantine buddy',
        category: 'Shakes',
        price: 16.99,
        img: 'https://smoothie.school/app/uploads/2020/04/Oreo-Nutella-Milkshake.jpg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    }
];
export default menuData;